### ISSUE TITLE
trouble cloning wal-e repo with our non-standard id_github key

### ISSUE THREAD

**Issue by bcoe** [npm/ansible-pg-wale#1]
We should make it so you can set `id_github` rather than `id_rsa` as a config setting.

**Comment by mmalecki** [comment]
@bcoe should be fixed by 8a827b5fc1213cdaf5b4c22c9ac024d289eb7650

**Comment by issa-tseng** [comment]
Looks like this change hasn't been published to `ansible-galaxy`; that would be much appreciated! Easy to work around in the meantime, of course. Thanks for the work.
